# Module 10 - Organizing and Analyzing Data with NumPy and Pandas


**_Author: Jessica Cervi_**


**Expected time = 2.5 hours**

**Total points = 100 points**



    
## Assignment Overview

In this assignment, we will use two important packages for data science with Python: NumPy and Pandas. With NumPy, you will conduct some more advanced operations such as matrix multiplication and transposition. With Pandas, you will learn how to work with the Pandas datareader to create DataFrames from remote data.


This assignment is designed to build your familiarity and comfort coding in Python while also helping you review key topics from each module. As you progress through the assignment, answers will get increasingly complex. It is important that you adopt a data scientist's mindset when completing this assignment. **Remember to run your code from each cell before submitting your assignment.** Running your code beforehand will notify you of errors and give you a chance to fix your errors before submitting. You should view your Vocareum submission as if you are delivering a final project to your manager or client. 

***Vocareum Tips***
- Do not add arguments or options to functions unless you are specifically asked to. This will cause an error in Vocareum.
- Do not use a library unless you are expicitly asked to in the question. 
- You can download the Grading Report after submitting the assignment. This will include feedback and hints on incorrect questions. 


### Learning Objectives

- Import data using Python
- Describe common Python packages
- Conduct simple statistical analysis on your data in Python 								


## Index: 

#### Module 10: Organizing and Analyzing Data with NumPy and Pandas

- [Question 1](#q1)
- [Question 2](#q2)
- [Question 3](#q3)
- [Question 4](#q4)
- [Question 5](#q5)
- [Question 6](#q6)
- [Question 7](#q7)
- [Question 8](#q8)
- [Question 9](#q9)
- [Question 10](#q10)
- [Question 11](#q11)
- [Question 12](#q12)
- [Question 13](#q13)
- [Question 14](#q14)
- [Question 15](#q15)
- [Question 16](#q16)
- [Question 17](#q17)
- [Question 18](#q18)
- [Question 19](#q19)

## Module 10: Organizing and Analyzing Data with NumPy and Pandas

We will begin to explore some specific applications using basic `NumPy` and `Pandas` functionality, to help us prepare for modeling work later in the course.  We will work with financial data using `NumPy` to perform basic operations and use `Pandas` for data manipulation. 

### Creating an `array()`

To begin, let's review the basics with `NumPy`.  This includes working with the `array` object, so let's begin by creating an array to represent the values from the data table below.

| RGSE | TAN | CMG | FLSR |
| ----- | ----- | ----- | ----- |
| 0.34 | 1.2 | 4.3 | 2.2 |
| 0.35 | 1.2 | 4.5 | 1.8 | 
| 0.38 | 1.2 | 4.8 | 1.7 |
| 0.35 | 1.1 | 4.9 | 1.2 | 

Remember that `NumPy` arrays support element-wise operations that can be performed via the functions `.sum()`, `.mean()` and so on.

Next, we import the `NumPy` library.

In [1]:
import numpy as np

[Back to top](#Index:) 
<a id='q1'></a>

### Question 1:

*5 points*
    
Using `np.array()`, create a `NumPy` array to match the one in the example above. Save your answer to `ans1` below.

In [3]:
ans1 = np.array([[0.34,1.2,4.3,2.2],\
                [0.35,1.2,4.5,1.8],\
                [0.38,1.2,4.8,1.7],\
                [0.35,1.1,4.9,1.2]])

In [4]:
ans1

array([[0.34, 1.2 , 4.3 , 2.2 ],
       [0.35, 1.2 , 4.5 , 1.8 ],
       [0.38, 1.2 , 4.8 , 1.7 ],
       [0.35, 1.1 , 4.9 , 1.2 ]])

In [5]:
### GRADED

### YOUR SOLUTION HERE
ans1 = np.array([[0.34,1.2,4.3,2.2],\
                [0.35,1.2,4.5,1.8],\
                [0.38,1.2,4.8,1.7],\
                [0.35,1.1,4.9,1.2]])

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q2'></a>

### Question 2:

*5 points*

Find the sum of the entries in the array `ans1` from Question 1. Assign the result to `ans2` as a float.
    

In [6]:
### GRADED

### YOUR SOLUTION HERE
ans2 = ans1.sum()

###
### YOUR CODE HERE
###


In [7]:
ans2

31.520000000000003

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q3'></a>

### Question 3:

*5 points*

Find the sum of the columns in the array `ans1` from Question 1 by setting the argument `axis=1`. Save your solution to `ans3` below.
    

In [8]:
### GRADED

### YOUR SOLUTION HERE
ans3 = ans1.sum(axis=1)

###
### YOUR CODE HERE
###


In [9]:
ans3

array([8.04, 7.85, 8.08, 7.55])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q4'></a>

### Question 4:

*5 points*

Find the sum of the rows in the array `ans1` from Question 1 by setting the argument `axis=0`. Save your solution to `ans4` below.

In [10]:
### GRADED

### YOUR SOLUTION HERE
ans4 = ans1.sum(axis=0)

###
### YOUR CODE HERE
###


In [11]:
ans4

array([ 1.42,  4.7 , 18.5 ,  6.9 ])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q5'></a>

### Question 5:

*5 points*

Using the logic from the previous questions,determine the mean of each column in the array `ans1` from Question 1 by using the .mean() method and axis argument. Save your results to `ans5` below.

In [12]:
### GRADED

### YOUR SOLUTION HERE
ans5 = ans1.mean(axis=1)

###
### YOUR CODE HERE
###


In [15]:
ans5

array([2.01  , 1.9625, 2.02  , 1.8875])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q6'></a>

### Question 6:

*5 points*

Using the logic from the previous questions, determine the standard deviation of each column in the array `ans1` from Question 1 by using the .mean() method and axis argument. Save your results to `ans6` below.

In [13]:
### GRADED

### YOUR SOLUTION HERE
ans6 = ans1.std(axis=1)

###
### YOUR CODE HERE
###


In [14]:
ans6

array([1.47692248, 1.55297094, 1.67278211, 1.77001942])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## Array Indexing

Indexing can be done in `NumPy` by using an array as an index. Index arrays must be made up of the integer data type. Each value in the array indicates which array value to use in place of the index. 

[Back to top](#Index:) 
<a id='q7'></a>

### Question 7:

*5 points*

Slice the last row of  the array `ans1` from Question 1 using the appropriate indicies. Save your results to `ans7` below.

In [23]:
ans1

array([[0.34, 1.2 , 4.3 , 2.2 ],
       [0.35, 1.2 , 4.5 , 1.8 ],
       [0.38, 1.2 , 4.8 , 1.7 ],
       [0.35, 1.1 , 4.9 , 1.2 ]])

In [22]:
ans1[3,:]

array([0.35, 1.1 , 4.9 , 1.2 ])

In [ ]:
### GRADED

### YOUR SOLUTION HERE
ans7 = ans1[3,:]

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q8'></a>

### Question 8:

*5 points*

Multiply the array `ans1` from Question 1 by 1.03. Save the resulting array to `ans8` below.

In [26]:
### GRADED

### YOUR SOLUTION HERE
ans8 = ans1*1.03

###
### YOUR CODE HERE
###


In [27]:
ans8

array([[0.3502, 1.236 , 4.429 , 2.266 ],
       [0.3605, 1.236 , 4.635 , 1.854 ],
       [0.3914, 1.236 , 4.944 , 1.751 ],
       [0.3605, 1.133 , 5.047 , 1.236 ]])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q9'></a>

## Identity Matrix
An identity matrix is a matrix with diagonal element equal to 1 and zero otherwise.

### Question 9:

*5 points*

Using the function `np.identity()`, build an identity matrix with the same dimensions as array `ans1` from Question 1. Save your matrix to ans9 below.


In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
### GRADED

### YOUR SOLUTION HERE
ans9 = np.identity(4)

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q10'></a>

## Transpose

The transpose of a matrix is a new matrix whose rows are the columns of the original and whose columns of the new matrix are the rows of the original.

### Question 10:

*5 points*

Use the array `ans1` from Question 1 and find find its transpose using the `.T` attribute.  Save your transposed array to `ans10` below.

In [30]:
### GRADED

### YOUR SOLUTION HERE
ans10 = ans1.transpose()

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q11'></a>

## Dot product

Algebraically, the dot product is the sum of the products of the corresponding entries of the two sequences of numbers (arrays). 

### Question 11:

*5 points*

Save the results of the dot product of the array `ans1` from Question 1 with the identity of itself to `ans11` below.

In [31]:
### GRADED

### YOUR SOLUTION HERE
ans11 = np.dot(ans1, np.identity(4))

###
### YOUR CODE HERE
###


In [ ]:
np.linalg.in

In [32]:
ans11

array([[0.34, 1.2 , 4.3 , 2.2 ],
       [0.35, 1.2 , 4.5 , 1.8 ],
       [0.38, 1.2 , 4.8 , 1.7 ],
       [0.35, 1.1 , 4.9 , 1.2 ]])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## Pandas and Time Series

In this section, we use Pandas to examine a `dataframe` of stock prices in a manner similar to that introduced in the lectures. 

We begin by importing the `pandas` library.

In [35]:
import pandas as pd

Net, we read the database and we visualize the first five rows.

In [37]:
stocks = pd.read_csv('data/tickers.csv', index_col=0)

In [38]:
stocks.head()

cmg        tan       flsr     rgse
date                                                 
2014-05-19  501.290009  33.851028  59.830002  27720.0
2014-05-20  495.649994  33.168442  58.630001  26280.0
2014-05-21  504.179993  34.892876  60.389999  24960.0
2014-05-22  520.479980  35.764076  60.630001  27840.0
2014-05-23  522.320007  36.356853  60.669998  28080.0

[Back to top](#Index:) 
<a id='q12'></a>

### Question 12:

*5 points*

Use the attribute `.describe` to examine the descriptive statistics of the DataFrame `stocks`.  Save your answer as a dataframe to `ans12` below.

In [40]:
### GRADED

### YOUR SOLUTION HERE
ans12= stocks.describe()

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q13'></a>

### Question 13:

*5 points*

Use the attribute `.memory_usage` to examine the information about the features of the dataframe `stocks`.  Save your answer as a dataframe to `ans13` below.

In [42]:
### GRADED

### YOUR SOLUTION HERE
ans13= stocks.memory_usage()

###
### YOUR CODE HERE
###


In [43]:
ans13

Index    10072
cmg      10072
tan      10072
flsr     10072
rgse     10072
dtype: int64

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q14'></a>

### Question 14:

*5 points*

Use the attribute `.pct_change()` to generate a new dataframe with the percent change for each ticker. Save your answer as dataframe to `ans14` below.

In [46]:
### GRADED

### YOUR SOLUTION HERE
ans14= stocks.pct_change()

###
### YOUR CODE HERE
###


In [47]:
ans14

cmg       tan      flsr      rgse
date                                              
2014-05-19       NaN       NaN       NaN       NaN
2014-05-20 -0.011251 -0.020164 -0.020057 -0.051948
2014-05-21  0.017210  0.051990  0.030019 -0.050228
2014-05-22  0.032330  0.024968  0.003974  0.115385
2014-05-23  0.003535  0.016575  0.000660  0.008621
...              ...       ...       ...       ...
2019-05-13 -0.025757 -0.037810 -0.026504  0.000000
2019-05-14  0.023150  0.011871  0.015925  0.363636
2019-05-15  0.003854  0.020227  0.008933  0.000000
2019-05-16  0.004307  0.024980  0.013532  0.066667
2019-05-17  0.009846 -0.023211 -0.037745 -0.062500

[1259 rows x 4 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q15'></a>

### Question 15:

*5 points*


The default period in our `.pct_change()` method is one day. This shows the percentage change in one day. We want a broader window, so we need to change this to a weekly (5 days) percent change by entering an appropriate period value.

Generate a dataframe representing the weekly percent change in price data. Save your results as a dataframe to `ans15` below.

In [48]:
### GRADED

### YOUR SOLUTION HERE
ans15= stocks.pct_change(5)

###
### YOUR CODE HERE
###


In [49]:
ans15

cmg       tan      flsr      rgse
date                                              
2014-05-19       NaN       NaN       NaN       NaN
2014-05-20       NaN       NaN       NaN       NaN
2014-05-21       NaN       NaN       NaN       NaN
2014-05-22       NaN       NaN       NaN       NaN
2014-05-23       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...
2019-05-13 -0.041023 -0.043836 -0.031348  0.571429
2019-05-14 -0.004727 -0.054685 -0.038256  1.142857
2019-05-15 -0.005186 -0.020963 -0.007791  0.875000
2019-05-16  0.005389  0.041499  0.029701  1.000000
2019-05-17  0.014842 -0.005514 -0.026838  0.363636

[1259 rows x 4 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q16'></a>

### Question 16:

*5 points*

In Question 15, we changed the time window for `.pct_change()`. To build off of that work, we can use the `.rolling()` method on a `dataframe` to group the data based on this time window.  We then perform an aggregate operation on the data.  For example, we can compute the rolling mean within a 20 day window. Note that this means 20 market days, not including weekends or holidays when the market is closed.

Use the `.rolling()` method together with the `.mean()` method to generate a dataframe with the rolling means for each
ticker.  Save your answer as a dataframe to `ans16` below

In [53]:
### GRADED

### YOUR SOLUTION HERE
ans16= stocks.pct_change().rolling(window=5).mean()

###
### YOUR CODE HERE
###


In [54]:
ans16

cmg       tan      flsr      rgse
date                                              
2014-05-19       NaN       NaN       NaN       NaN
2014-05-20       NaN       NaN       NaN       NaN
2014-05-21       NaN       NaN       NaN       NaN
2014-05-22       NaN       NaN       NaN       NaN
2014-05-23       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...
2019-05-13 -0.008284 -0.008553 -0.006108  0.103571
2019-05-14 -0.000822 -0.010876 -0.007567  0.176299
2019-05-15 -0.000914 -0.003848 -0.001372  0.147727
2019-05-16  0.001199  0.008447  0.006009  0.161061
2019-05-17  0.003080 -0.000789 -0.005172  0.073561

[1259 rows x 4 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q17'></a>

### Question 17:

*10 points*

Now, let's combine our percent change calculation to create a new column that identifies whether or not a stock had a positive or negative percent change.  You must first write a function called `up_or_down` that takes in a dataframe object and returns a dataframe object whose values are a count of the periods, by column, of positive percent change.

For example, if a stock `tan` had 222 days of positive percent change, we'd see a returned Series object that may look like this:

```
cmg     111
tan     222
flsr    333
rgse    444
dtype: int64
```

Save _your function_ to `ans17`. Note that functions can be saved to variables in python. Your variable will subsequently be called by a testing utility, using the dataframe input, to verify the output.

In [ ]:
### GRADED

### YOUR SOLUTION HERE
def up_or_down(df):
    import pandas as pd
    '''
    This function takes in a value
    and returns a 0 if the value is
    negative and a 1 where the value is
    positive.
    '''
    return

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q18'></a>

### Question 18:

*5 points*

Examine the correlations between percent change in ticker symbols using the `.corr()` method on the dataframe `stocks`.  Save your results as a dataframe to `ans18` below.

In [ ]:
### GRADED

### YOUR SOLUTION HERE
ans18= None

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 
<a id='q19'></a>

### Question 19:

Using the assumption that correlated stocks are not good to have in a single portfolio, determine whether there are any symbol(s) you should drop if you own **tan**.

Using the `.corr()` dataframe on percent change, determine  if any symbols correlation with tan is above 0.5.  Save the symbols as set of strings below, i.e. {'cmg', 'flsr'}

In [ ]:
### GRADED

### YOUR SOLUTION HERE
ans19 = None

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Linear Regression using `statsmodels.api`

Next, let's try some regression using the `statsmodels.api` implementation of Linear Regression. To begin, we import the necessary library and will save our `X` and `y` variables.  

In [ ]:
import statsmodels.api as sm

X= pd.read_csv('data/tickers.csv', index_col=0).pct_change().dropna().drop('tan', axis=1)
y = pd.read_csv('data/tickers.csv', index_col=0).pct_change().dropna()['tan']

Now, we prepare our input features by adding a constant term for the intercept term.  We do this using the `.add_constant()` method.

In [ ]:

X_const = sm.add_constant(X)

After adding our constant term to our feature matrix, we are ready to fit a model.  With statsmodels, this is a two step process.  First, we instantiate an empty model class with `sm.OLS()`.  

In [ ]:
model = sm.regression.linear_model.OLS(y_ans, X_ans)


Now that we've instantiate a model, we can fit the model using the `.fit()` method.  Once fit, you can see the summary of the model using the `.summary()` method of the variable you saved the fit model to.

```python
model = sm.OLS(y, X)  # Note that y comes first!
res = model.fit()
```

In [ ]:
res = model.fit()



Finally, we can examine the confidence intervals for each of our coefficients.  We are interested in whether or not 0 appears inside of the interval.  If so, we fail to reject the null hypothesis that the coefficient is zero.


In [ ]:
res_ans = model.fit()