<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [5]:
import numpy as np
ax = np.array([1,2,3,4,5]) # Converts to array
print(ax,id(ax),len(ax))
type(ax)

[1 2 3 4 5] 140154352367216 5


numpy.ndarray

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [8]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<h2>Basic operations</h2>

In [9]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h2>Multi-dimensional arrays</h2>

In [11]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [12]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [13]:
ax[1:3,2:4]
#ax[:,2:]

array([[12., 13.],
       [22., 23.]])

<h3>Reshaping</h3>


In [21]:
print(ax.shape)
# We can reshape the array
ax.reshape(9,2)
# Number of elements must be the same
ax.reshape(6,3)

(3, 6)


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [10., 11., 12.],
       [13., 14., 15.],
       [20., 21., 22.],
       [23., 24., 25.]])

<h3>Creating initialized arrays</h3>

In [22]:
# All the elements from 0 - 9, like the range in python
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [23]:
ax = np.ones(10)
print(ax)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [24]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


In [25]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<h3>Matrix multiplication</h3>


In [26]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [27]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h3>Comparing numpy arrays with lists</h3>

In [29]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
print(ax)
ay = ax.transpose()
#print(ax)
#print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]


array([[ 15333, 120825],
       [120825, 978405]])

<h4>Functionalize this</h4>


In [34]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0, 0, 26)

<h4>Do the same with python lists</h4>


In [35]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10000)

datetime.timedelta(0, 0, 22406)

In [41]:
for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')
# We can see that numpy is very fast and it scales almost linnearly

10	0:00:00.000030	0:00:00.000038
100	0:00:00.000017	0:00:00.000110
1000	0:00:00.000024	0:00:00.003776
10000	0:00:00.000125	0:00:00.029143


<h3>Selecting elements from an np array</h3>

In [45]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
# go through the array, for every even number put a 1, otherwise we put a 0
# we look at each element of the array and create a new array
print(ax)
np.where(ax%2==0,1,0)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [46]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [51]:
import scipy
scipy.nanmean(x)

/home/alexei/ds/eme/pro/my_project_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.nanmean is deprecated and will be removed in SciPy 2.0.0, use numpy.nanmean instead
  


12.5

<h3>Random number support in numpy</h3>

In [54]:
np.random.normal(size=10)
# 100 by 100 matrix
np.random.normal(size=(100,100))
np.random.exponential()
# Exponentially distributed random variables
np.random.exponential(1.0,size=(6,3))
# 9 x 9 values
np.random.randint(-10,10,size=(9,9))

array([[  3,   7,   8,   0,  -8,  -8,   6, -10,   7],
       [  8,  -4,   1,  -9,   4,  -9,  -7,   8,   9],
       [ -5,   7,  -4,  -9,  -7,  -7,   5,   9, -10],
       [  1,  -5,   4,  -3,   7,  -2,   7,  -8,   4],
       [ -9,   6,  -3,   7,   4,   1,   7,  -4,   2],
       [ -1,   9,  -3,  -9,  -2,  -1,   2,  -9,  -4],
       [ -2,   8,  -8,  -4,   7,  -3, -10,  -4,  -6],
       [ -7,  -3,   2,   6,  -4,   6,   2,  -8,   1],
       [ -4,  -9,   7,   7,   4,  -9,  -7,  -1,   1]])

In [55]:
np.loadtxt('testfile.txt')

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.]])

In [66]:
a =[['a','b','c'],['a','b','c']]
a

[['a', 'b', 'c'], ['a', 'b', 'c']]

In [67]:
a[2][1] = np.char.replace(a[2][1],'a','e')

IndexError: list index out of range

In [74]:
Z = np.arange(9).reshape(3,3)

In [75]:
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])