# Module 4 - Popular Data Science Packages in Python

**_Author: Jessica Cervi_**

**Expected time = 1.5 hours**

**Total points = 90 points**


## Assignment Overview


In this assignment you will work with the material you learned in Module 4, packages scripts, such as the `Numpy` and `pandas` librariers. You will learn how to import packages and how to use their functions. You will also test your knowledge on 1D and 2D `NumPy` arrays. In the second half of the assignment, you will be asked to work with DataFrames.  You will be asked to create DataFrames and to select dataseries. Finally, you will be asked to filter the data in a DataFrame and compute basic statistic on its entries.


This assignment is designed to build your familiarity and comfort coding in Python while also helping you review key topics from each module. As you progress through the assignment, answers will get increasingly complex. It is important that you adopt a data scientist's mindset when completing this assignment. Remember to run your code from each cell before submitting your assignment. Running your code beforehand will notify you of errors and give you a chance to fix them before submitting. You should view your Vocareum submission as if you are delivering a final project to your manager or client.

**Vocareum Tips**

- Do not add arguments or options to functions unless you are specifically asked to. This will cause an error in Vocareum.
- Do not use a library unless you are expicitly asked to in the question.
- You can download the Grading Report after submitting the assignment. This will include feedback and hints on incorrect questions.


### Learning Objectives

 - Import and use packages in Jupyter Notebooks. 
 - Distinguish between NumPy arrays and lists. 
 - Use NumPy functions for basic statistical analyses. 
 - Practice filtering and slicing DataFrames with pandas. 




## Index:

#### Module 4: Popular Data Science Packages in Python

- [Question 1](#Question-1)
- [Question 2](#Question-2)
- [Question 3](#Question-3)
- [Question 4](#Question-4)
- [Question 5](#Question-5)
- [Question 6](#Question-6)
- [Question 7](#Question-7)
- [Question 8](#Question-8)
- [Question 9](#Question-9)
- [Question 10](#Question-10)
- [Question 11](#Question-11)
- [Question 12](#Question-12)
- [Question 13](#Question-13)
- [Question 14](#Question-14)
- [Question 15](#Question-15)
- [Question 16](#Question-16)



## Module 4: Popular Data Science Packages in Python


In this assignment, we will be testing your knowledge of the topics covered in Module 4, such as importing packages, Numpy arrays, pandas DataFrames. Finally, we will test your knowledge about subsetting anf filtering DataFrames and about applying Numpy statistical functions to a Dataframe.

### Importing packages and functions, aliasing
We will begin this assignment with a review of the `NumPy` and `pandas` libraries. As you have learned, `NumPy` is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices and `pandas` is a software library written for the Python programming language for data manipulation and analysis. We will start with some basic questions about aliasing a package and importing functions.

[Back to top](#Index:) 

### Question 1

5 points 

What is the correct syntax to use if you want to alias the library `Numpy` using `np` in your code? 
    - a) use numpy like np
    - b) import numpy as np
    - c) from numpy import np
    - d) use np like numpy

Assign the character  associated with your answer as a string to `ans1`. For, example if you believe `a` is the correct answer, submit yur answer as `ans1 = a`.

In [6]:
### YOUR SOLUTION HERE
ans1 = "b"

###
### YOUR CODE HERE
###


In [7]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 2

5 points 

What is the correct syntax to use if you want to alias the library  `pandas` using `pd` in your code? 
    - a) import Pandas as pd 
    - b) use pandas a pd
    - c) import pandas as pd
    - d) from pandas use pd

Assign the character associated with your answer as a string to `ans2`. For, example if you believe `a` is the correct answer, submit yur answer as `ans2 = a`.

In [8]:
### YOUR SOLUTION HERE
ans2 = "c"

###
### YOUR CODE HERE
###


In [9]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 3

5 points 

What is the correct syntax to use if you want to import just the function .square() from `NumPy`? 
    - a) from numpy import .square()
    - b) from numpy get square
    - c) use square from numpy
    - d) from numpy import square

Assign the character associated with your answer as a string to `ans3`.

In [1]:
from numpy import square

In [14]:
### YOUR SOLUTION HERE
ans3 = "d"

###
### YOUR CODE HERE
###


In [15]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### The NumPy library
NumPy is a Python package that stands for Numeric Python. The most useful tool in this package is a new data type called an array. Numpy also comes with sophisticated functions and linear algebra and random number capabilities.
In the next questions, we will learn how to create numpy arrays, how to perform basic operations on them, and how to slice them.

You can find more information about the `NumPy` package [here](https://numpy.org/doc/1.18/reference/index.html).


**Note: Questions 4, 5, 6, and 7 are connected and must to be answered in sequence.**

[Back to top](#Index:) 

### Question 4
5 points 

Given `distance=[2000,4000,6000,7000,1000]`, use `np.array()` to create a numpy array from `distance`. Name this array `np_distance`.

In [17]:
#impoting numpy and pandas
import numpy as np
import pandas as pd

In [18]:
distance=[2000,4000,6000,7000,1000]

### YOUR SOLUTION HERE
np_distance = np.array(distance)

###
### YOUR CODE HERE
###


In [20]:
np_distance

array([2000, 4000, 6000, 7000, 1000])

In [19]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 5
5 points 

Divide `np_distance` by 1000 to obtain the distance in kilometers. Name this array `np_distance_km`.

In [25]:
### YOUR SOLUTION HERE
np_distance_km = np_distance/1000

###
### YOUR CODE HERE
###


In [27]:
print(np_distance_km)

[2. 4. 6. 7. 1.]


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 6
5 points 

Given time=[0.5, 1,1.3,1.5,2], use `np.array()` to create a numpy array from time. Name this array `np_time`. Next, divide `np_distance_km` by `np_time`. Name this array `np_velocity`.



In [29]:
time=[0.5, 1,1.3,1.5,2]

### YOUR SOLUTION HERE
np_time = np.array(time)
np_velocity = np_distance_km/np_time

###
### YOUR CODE HERE
###


In [30]:
print(np_velocity)

[4.         4.         4.61538462 4.66666667 0.5       ]


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 7
5 points 

Because we got some new new information about ora data, change the second last element of `np_velocity` to 1.8. Name this array `np_velocity_fixed`.


In [31]:
np_velocity

array([4.        , 4.        , 4.61538462, 4.66666667, 0.5       ])

In [33]:
### YOUR SOLUTION HERE
np_velocity[-2] = 1.8
np_velocity_fixed = np_velocity

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Getting started with NumPy 2D arrays

In `NumPy`, rather than creating a numpy array with 1 dimension, you can create arrays that have more than one dimension. In the next questions you will work with 2D numpy arrays and retrieve the data you want from it.  


**Note: Questions 8, 9, 10, and 11 are connected and must be answered in sequence.**

[Back to top](#Index:) 

### Question 8
5 points 

`body_measurement`, defined below, contains 4 body measurements of four students. Each of these elements is a list containing the height and the weight of 4 students.
Given body_measurement defined below, use `np.array()` to create a 2D NumPy array from body_measurement. Name it `np_body_measurement`.


In [34]:
body_measurement = [[168, 55.4],
            [155, 47.7],
            [175, 69.5],
            [189, 90.2]]

### YOUR SOLUTION HERE
np_body_measurement= np.array(body_measurement)

###
### YOUR CODE HERE
###


In [36]:
np_body_measurement

array([[168. ,  55.4],
       [155. ,  47.7],
       [175. ,  69.5],
       [189. ,  90.2]])

In [35]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 9
5 points 

Use the numpy function `shape` to get the shape of `np_body_measurement`. Assign the shape to the variable `ans9`.

In [38]:
### YOUR SOLUTION HERE
ans9= np.shape(np_body_measurement)

###
### YOUR CODE HERE
###


In [39]:
ans9

(4, 2)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 10
5 points 


Select the body measurments of the second student in np_body_measurement and assign it to `second_student`.


In [42]:
### YOUR SOLUTION HERE
second_student= np_body_measurement[1:2]

###
### YOUR CODE HERE
###


In [43]:
second_student

array([[155. ,  47.7]])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 11
5 points 


Select the weight of the third student in np_body_measurement and assign it to `weight_third_student`.

In [48]:
### YOUR SOLUTION HERE
weight_third_student= np_body_measurement[2,1]

###
### YOUR CODE HERE
###


In [49]:
weight_third_student

69.5

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Getting started with Pandas and Numpy statistical tools

`Pandas` is a very powerful Python library designed to analize and manipulate data. A very important data type that `pandas` allow to create are pandas DataFrame. A DataFrame is a data structure that allows you to store different data types in rows and columns. In the next questions, we will learn how to create, subset, and slice DataFrames. Finally, you will be asked to perform some basic statistic on pandas DataFrame using NumPy tools.

You can find more information about the `Pandas` package [here](https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html#getting-started).

**Note: Questions 14,15 and 16 are connected and must be answered in sequence.**


[Back to top](#Index:) 

### Question 12
5 points 

Convert `museum`, given below, to a pandas DataFrame. Name the dataframe `df_museum`

In [50]:
museum = {
    'museum':['Louvre','Hermitage','National Gallery','Metropolitan'],
    'Picasso':[True,False,True,False]
}

### YOUR SOLUTION HERE
df_museum= pd.DataFrame(museum)

###
### YOUR CODE HERE
###


In [73]:
print(df_museum)

             museum  Picasso
0            Louvre     True
1         Hermitage    False
2  National Gallery     True
3      Metropolitan    False


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 13
5 points 

Assume that a database is saved as `students.csv`. What is the correct syntax to use in pandas to load the database into a pandas DataFrame called `df_students`?

    - a) df_students = pd.read_csv("students.csv")
    - b) df_students = pd.DataFrame("students.csv")
    - c) df_students = pd.csv_to_df("students.csv")
    - d) df_students= pd.to_df("students.csv")

Assign the character associated with your answer as a string to `ans13`.

In [52]:
### YOUR SOLUTION HERE
ans13= "a"

###
### YOUR CODE HERE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 14
5 points 

For this question, we will use an open source database that collects some health information about patients. Information about the dataset can be found [here](https://www.kaggle.com/burmad/patient#Patient%20Data.csv).

Read the CSV file named `"patients.csv"` in the `data/` folder and assign it to a dataframe called `df_patients`.
Next, extract the columns `gender`, `age`, and `BMI` in the **specified order** and assign them to a new DataFrame called `df_patients_main`.

In [57]:
### YOUR SOLUTION HERE
df_patients= pd.read_csv("data/patients.csv")
df_patients_main = df_patients[["gender", "age", "BMI"]]

###
### YOUR CODE HERE
###


In [59]:
df_patients_main

gender   age    BMI
0      Female  80.0  25.19
1      Female  54.0    NaN
2        Male  28.0    NaN
3      Female  36.0  23.45
4        Male  76.0  20.14
...       ...   ...    ...
99995  Female  80.0    NaN
99996  Female   2.0  17.37
99997    Male  66.0  27.83
99998  Female  24.0  35.42
99999  Female  57.0  22.43

[100000 rows x 3 columns]

In [55]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 15
10 points


Take the dataframe `df_patients_main` and create a filter to get all rows where the column `age` is less or equal than 30. Call this new dataframe `df_patients_u30`.

In [63]:
### YOUR SOLUTION HERE
less_30 = df_patients_main["age"]<=30
df_patients_u30 = df_patients_main[less_30]

###
### YOUR CODE HERE
###


In [71]:
df_patients_u30

gender   age    BMI
2        Male  28.0    NaN
5      Female  20.0    NaN
16       Male  15.0  30.36
21       Male   5.0  18.80
24     Female   4.0  13.99
...       ...   ...    ...
99989  Female  26.0    NaN
99991    Male  22.0  29.65
99992  Female  26.0  34.34
99996  Female   2.0  17.37
99998  Female  24.0  35.42

[33733 rows x 3 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 16
5 points 

Compute the average of the column `BMI` from the DataFrame `df_patients` and assign the value to the variable `average_bmi`.

In [65]:
### YOUR SOLUTION HERE
average_bmi = np.mean(df_patients["BMI"])

###
### YOUR CODE HERE
###


In [66]:
average_bmi

27.321028891034924

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [ ]:
array