# Office Hours: Jacob on 5-4

In [12]:
import numpy as np
import pandas as pd

In [8]:
a = np.arange(10).reshape(5, 2)

In [9]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
a.shape

(10,)

In [7]:
a.reshape(5, 2).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [10]:
np.apply_along_axis()

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
def is_the_product_a_two(x):
    if x[0]*x[1] == 2:
        return 'Yup'
    else:
        return 'Not sure man'

In [29]:
pd.DataFrame(a).apply(is_the_product_a_two, axis = 1)

0    Not sure man
1    Not sure man
2    Not sure man
3    Not sure man
4    Not sure man
dtype: object

In [30]:
import seaborn as sns

In [31]:
tips = sns.load_dataset('tips')

In [33]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
tips['pct_tip'] = tips['tip']/tips['total_bill']

In [35]:
tips.head()

total_bill   tip     sex smoker  day    time  size   pct_tip
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

In [45]:
def the_weekend_and_dinner(x):
    if x[0] in ['Sat', 'Sun'] and x[1] == 'Dinner':
        return 'Yes!!!!!'
    else:
        return x[2]

In [46]:
tips[['day', 'time', 'size']].apply(the_weekend_and_dinner, axis = 1)

0      Yes!!!!!
1      Yes!!!!!
2      Yes!!!!!
3      Yes!!!!!
4      Yes!!!!!
         ...   
239    Yes!!!!!
240    Yes!!!!!
241    Yes!!!!!
242    Yes!!!!!
243           2
Length: 244, dtype: object

In [41]:
tips.tail()

total_bill   tip     sex smoker   day    time  size   pct_tip
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

In [55]:
np.mean(a, axis = 0)

array([4., 5.])

In [52]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
tips.replace({'Male': 0, 'Female': 1})

total_bill   tip  sex smoker   day    time  size   pct_tip
0         16.99  1.01    1     No   Sun  Dinner     2  0.059447
1         10.34  1.66    0     No   Sun  Dinner     3  0.160542
2         21.01  3.50    0     No   Sun  Dinner     3  0.166587
3         23.68  3.31    0     No   Sun  Dinner     2  0.139780
4         24.59  3.61    1     No   Sun  Dinner     4  0.146808
..          ...   ...  ...    ...   ...     ...   ...       ...
239       29.03  5.92    0     No   Sat  Dinner     3  0.203927
240       27.18  2.00    1    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    0    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    0     No   Sat  Dinner     2  0.098204
243       18.78  3.00    1     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

In [ ]:
def f(x):
    
    def g(x):
        return x + 7
    return [g(a) for a in x]

In [57]:
a = 8

In [63]:
def f(x):
    a = 10
    return x + a

In [65]:
a

9

In [64]:
f(4)

14

In [60]:
f(6)

14

In [61]:
a = 9

In [62]:
f(4)

13